// <auto-generated />
using System;
using FanSite.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FanSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("FanSite.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UserStoryID");

                    b.HasKey("CommentID");

                    b.HasIndex("UserStoryID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FanSite.Models.MediaRef", b =>
                {
                    b.Property<int>("MediaRefID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LinkURL");

                    b.Property<string>("MediaType");

                    b.Property<string>("SourceName");

                    b.HasKey("MediaRefID");

                    b.ToTable("MediaRefs");
                });

            modelBuilder.Entity("FanSite.Models.UserStory", b =>
                {
                    b.Property<int>("UserStoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("StoryPost")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("UserStoryID");

                    b.ToTable("UserStories");
                });

            modelBuilder.Entity("FanSite.Models.Comment", b =>
                {
                    b.HasOne("FanSite.Models.UserStory")
                        .WithMany("Comments")
                        .HasForeignKey("UserStoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
