// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorForum.Repositories;

namespace TutorForum.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191205042933_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TutorForum.Models.FAQuestion", b =>
                {
                    b.Property<int>("FAQuestionID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("QuestionBody");

                    b.Property<string>("QuestionHeader");

                    b.HasKey("FAQuestionID");

                    b.ToTable("FAQuestions");
                });

            modelBuilder.Entity("TutorForum.Models.ForumQuestion", b =>
                {
                    b.Property<int>("ForumQuestionID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("QuestionBody");

                    b.Property<string>("QuestionHeader");

                    b.Property<int?>("QuestionerMemberID");

                    b.HasKey("ForumQuestionID");

                    b.HasIndex("QuestionerMemberID");

                    b.ToTable("ForumQuestions");
                });

            modelBuilder.Entity("TutorForum.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Title");

                    b.Property<string>("UserName");

                    b.HasKey("MemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("TutorForum.Models.Reply", b =>
                {
                    b.Property<int>("ReplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<int?>("QuestionPostForumQuestionID");

                    b.Property<string>("ReplyBody");

                    b.Property<int?>("ResponderMemberID");

                    b.HasKey("ReplyID");

                    b.HasIndex("QuestionPostForumQuestionID");

                    b.HasIndex("ResponderMemberID");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("TutorForum.Models.Tutor", b =>
                {
                    b.Property<int>("TutorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Title");

                    b.Property<string>("UserName");

                    b.HasKey("TutorID");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("TutorForum.Models.ForumQuestion", b =>
                {
                    b.HasOne("TutorForum.Models.Member", "Questioner")
                        .WithMany("QuestionsAsked")
                        .HasForeignKey("QuestionerMemberID");
                });

            modelBuilder.Entity("TutorForum.Models.Reply", b =>
                {
                    b.HasOne("TutorForum.Models.ForumQuestion", "QuestionPost")
                        .WithMany("Replies")
                        .HasForeignKey("QuestionPostForumQuestionID");

                    b.HasOne("TutorForum.Models.Member", "Responder")
                        .WithMany("Answers")
                        .HasForeignKey("ResponderMemberID");
                });
#pragma warning restore 612, 618
        }
    }
}
